version: "3"
services:
  db:
    image: postgres:14.2-alpine
    container_name: whatsapp_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  whatsapp_bot:
    build:
      context: .
      args:
        ACCESS_TOKEN: ${ACCESS_TOKEN}
        APP_ID: ${APP_ID}
        APP_SECRET: ${APP_SECRET}
        RECIPIENT_WAID: ${RECIPIENT_WAID}
        VERSION: ${VERSION}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        PHONE_NUMBER_ID: ${PHONE_NUMBER_ID}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: "./bin/rails server -p 4010"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - APP_ID=${APP_ID}
      - APP_SECRET=${APP_SECRET}
      - RECIPIENT_WAID=${RECIPIENT_WAID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PHONE_NUMBER_ID=${PHONE_NUMBER_ID}
      - TZ=America/New_York
    volumes:
      - .:/rails
      - ./storage:/rails/storage
    depends_on:
      - db
    ports:
      - "4010:4010"

volumes:
  postgres_data: {}
